version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code

  redis:
    image: "redis:alpine"

#This Compose file defines two services, web and redis. The web service:
#
#Uses an image that’s built from the Dockerfile in the current directory.
#Forwards the exposed port 5000 on the container to port 5000 on the host machine. We use the default port for the Flask web server, 5000.
#The redis service uses a public Redis image pulled from the Docker Hub registry.

#The new volumes key mounts the project directory (current directory) on the host to /code inside the container, allowing you to modify the code on the fly